Jimm swisslogic 2
kenn581j/WHUT pull request #10
Opened 2019-05-10 00:29 UTC by jimm1034

Forsøgt at undgå merge konflikt, så vi kan få swiss sortering logikken implementeret. 

Der mangler stadig at tilføjes en metode til at omsortere hvis spilleren allerede har mødt modstanderen før.

2019-05-10 00:31 UTC, jimm1034 reviewed
Læg mærke til at alt rødt er hvad jeg har slettet, så kan være at merge konflikten opstår alligevel.. 
Jeg tager den hvis det sker

2019-05-14 01:06 UTC, jimm1034 commented
Min pull request er her

2019-05-14 09:54 UTC, kenn581j requested changes
See comment

2019-05-14 09:54 UTC, kenn581j commented on WHUT/Domain/Player.cs
> +        public Player(string name, string club, string warband, int score, int tieBreakerByLoss, int tieBreakerGloryDiff)
Player contructor skal da være uden score og tiebreakers? Når vi opretter en spiller, har vi ikke spillet en match endnu

2019-05-14 10:13 UTC, jimm1034 commented on WHUT/Domain/Player.cs
> +        public Player(string name, string club, string warband, int score, int tieBreakerByLoss, int tieBreakerGloryDiff)
Kommentar skrevet til konstruktør

2019-05-14 10:14 UTC, kenn581j approved these changes

2019-05-14 10:15 UTC, lise2108 approved these changes

2019-05-14 10:16 UTC, merged