RemoveParticipant()
kenn581j/WHUT pull request #11
Opened 2019-05-16 11:21 UTC by lise2108

2019-05-17 01:38 UTC, jimm1034 approved these changes

2019-05-17 02:14 UTC, jimm1034 requested changes
Jeg kunne desværre ikke få den til at virke, men jeg fandt en anden måde hvis det er - ved ikke om vi skal tage den allesammen sammen?

2019-05-17 02:15 UTC, jimm1034 commented on WHUT/Business/TournamentRepo.cs
> +       ////// SPØRG HANS ANGÅENDE FREMLÆGGELSE.
Lol

2019-05-22 09:30 UTC, kenn581j requested changes
Se komment

2019-05-22 09:30 UTC, kenn581j commented on WHUT/Business/TournamentRepo.cs
> +        public void RemoveParticipant(Player name)
UI har ikke adgang til player objects. Skal finde deltager på deres navn.

2019-05-30 17:20 UTC, closed without merging